### ISSUE TITLE
Crash Adding 1.18

### ISSUE THREAD

**Issue by DaggerTM** [PowerInMC/Croparia#5]
I've been havingthis crash once I add Croparia. I remove it and there is no crash

Log:

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
>   AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
>   EnderCorePlugin (EnderCore-1.12.2-0.5.31.jar)
>   LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
>   Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
>   SSLoadingPlugin (SereneSeasons-1.12.2-1.2.3-universal.jar)
> Contact their authors BEFORE contacting forge
> 
> // Ouch. That hurt :(
> 
> Time: 6/16/18 5:01 PM
> Description: There was a severe problem during mod loading that has caused the game to fail
> 
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)
> Caused by: java.lang.NullPointerException
> 	at net.minecraft.client.util.SearchTree.func_194039_a(SourceFile:48)
> 	at net.minecraft.client.util.SearchTree$$Lambda$937/474183557.accept(Unknown Source)
> 	at java.util.ArrayList.forEach(ArrayList.java:1249)
> 	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:48)
> 	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
> 	at net.minecraft.client.Minecraft$$Lambda$966/283390651.accept(Unknown Source)
> 	at java.util.ArrayList.forEach(ArrayList.java:1249)
> 	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:603)
> 	at net.minecraftforge.fml.client.FMLClientHandler.reloadSearchTrees(FMLClientHandler.java:1079)
> 	at net.minecraftforge.fml.common.FMLCommonHandler.reloadSearchTrees(FMLCommonHandler.java:772)
> 	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:562)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
> 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
> 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
> 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
> 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
> 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
> 	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
> 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
> 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
> 	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:924)
> 	at net.minecraftforge.registries.GameData.freezeData(GameData.java:237)
> 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:753)
> 	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:329)
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.12.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_25, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 1496061768 bytes (1426 MB) / 3081240576 bytes (2938 MB) up to 6203899904 bytes (5916 MB)
> 	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6656m -Xms256m -XX:PermSize=256m
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP 9.42 Powered by Forge 14.23.4.2708 Optifine OptiFine_1.12.2_HD_U_D2 91 mods loaded, 91 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 
> 	| State   | ID                                | Version                  | Source                                        | Signature                                |
> 	|:------- |:--------------------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
> 	| UCHIJA  | minecraft                         | 1.12.2                   | minecraft.jar                                 | None                                     |
> 	| UCHIJA  | mcp                               | 9.42                     | minecraft.jar                                 | None                                     |
> 	| UCHIJA  | FML                               | 8.0.99.99                | forge-1.12.2-14.23.4.2708.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCHIJAE | forge                             | 14.23.4.2708             | forge-1.12.2-14.23.4.2708.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| UCHIJA  | foamfixcore                       | 7.7.4                    | minecraft.jar                                 | None                                     |
> 	| UCHIJA  | codechickenlib                    | 3.1.9.344                | CodeChickenLib-1.12.2-3.1.9.344-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
> 	| UCHIJA  | ancientwarfare                    | 1.12.2-2.6.0.239         | ancientwarfare-1.12.2-2.6.0.239.jar           | None                                     |
> 	| UCHIJA  | ancientwarfareautomation          | 1.12.2-2.6.0.239         | ancientwarfare-1.12.2-2.6.0.239.jar           | None                                     |
> 	| UCHIJA  | ancientwarfarenpc                 | 1.12.2-2.6.0.239         | ancientwarfare-1.12.2-2.6.0.239.jar           | None                                     |
> 	| UCHIJA  | ancientwarfarestructure           | 1.12.2-2.6.0.239         | ancientwarfare-1.12.2-2.6.0.239.jar           | None                                     |
> 	| UCHIJA  | ancientwarfarevehicle             | 1.12.2-2.6.0.239         | ancientwarfare-1.12.2-2.6.0.239.jar           | None                                     |
> 	| UCHIJA  | applecore                         | 3.1.3                    | AppleCore-mc1.12.2-3.1.3.jar                  | None                                     |
> 	| UCHIJA  | crafttweaker                      | 4.1.8                    | CraftTweaker2-1.12-4.1.8.jar                  | None                                     |
> 	| UCHIJA  | mtlib                             | 3.0.5                    | MTLib-3.0.5.jar                               | None                                     |
> 	| UCHIJA  | modtweaker                        | 4.0.12                   | modtweaker-4.0.12.jar                         | None                                     |
> 	| UCHIJA  | jei                               | 4.10.0.198               | jei_1.12.2-4.10.0.198.jar                     | None                                     |
> 	| UCHIJA  | appleskin                         | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                    | None                                     |
> 	| UCHIJA  | mantle                            | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                      | None                                     |
> 	| UCHIJA  | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     |
> 	| UCHIJA  | endercore                         | 1.12.2-0.5.31            | EnderCore-1.12.2-0.5.31.jar                   | None                                     |
> 	| UCHIJA  | thaumcraft                        | 6.1.BETA16               | Thaumcraft-1.12.2-6.1.BETA16.jar              | None                                     |
> 	| UCHIJA  | enderio                           | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                     | None                                     |
> 	| UCHIJA  | enderiointegrationtic             | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                     | None                                     |
> 	| UCHIJA  | tconstruct                        | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar               | None                                     |
> 	| UCHIJA  | conarm                            | 1.0.0                    | conarm-1.12.2-1.0.0.jar                       | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
> 	| UCHIJA  | taiga                             | 1.3.2                    | taiga-1.12.2-1.3.2.jar                        | None                                     |
> 	| UCHIJA  | twilightforest                    | 3.7.424                  | twilightforest-1.12.2-3.7.424-universal.jar   | None                                     |
> 	| UCHIJA  | armoryexpansion                   | 0.1.4                    | armoryexpansion-0.1.4.jar                     | None                                     |
> 	| UCHIJA  | betteradvancements                | 0.0.5.17                 | BetterAdvancements-1.12.2-0.0.5.17.jar        | None                                     |
> 	| UCHIJA  | betterquesting                    | 3.5.259                  | BetterQuesting-3.5.259.jar                    | None                                     |
> 	| UCHIJA  | bookshelf                         | 2.3.552                  | Bookshelf-1.12.2-2.3.552.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
> 	| UCHIJA  | cosmeticarmorreworked             | 1.12.2-v1                | CosmeticArmorReworked-1.12.2-v1.jar           | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
> 	| UCHIJA  | ctgui                             | 1.0.0                    | CraftTweaker2-1.12-4.1.8.jar                  | None                                     |
> 	| UCHIJA  | crafttweakerjei                   | 2.0.2                    | CraftTweaker2-1.12-4.1.8.jar                  | None                                     |
> 	| UCHIJA  | croparia                          | 1.18                     | Croparia-1.18.jar                             | None                                     |
> 	| UCHIJA  | essentials                        | 1.12.2-1.0.0             | essentials-1.12.2-1.0.0.jar                   | None                                     |
> 	| UCHIJA  | crossroads                        | 1.12.2-1.8.0             | crossroads-1.12.2-1.8.0.jar                   | None                                     |
> 	| UCHIJA  | custommainmenu                    | 2.0.8                    | CustomMainMenu-MC1.12.2-2.0.8.jar             | None                                     |
> 	| UCHIJA  | mcjtylib_ng                       | 3.0.1                    | mcjtylib-1.12-3.0.1.jar                       | None                                     |
> 	| UCHIJA  | efab                              | 0.0.37                   | efab-0.0.37.jar                               | None                                     |
> 	| UCHIJA  | enderiobase                       | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                     | None                                     |
> 	| UCHIJA  | enderioconduits                   | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                     | None                                     |
> 	| UCHIJA  | enderioconduitsappliedenergistics | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                     | None                                     |
> 	| UCHIJA  | refinedstorage                    | 1.5.34                   | refinedstorage-1.5.34.jar                     | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
> 	| UCHIJA  | enderioconduitsopencomputers      | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                     | None                                     |
> 	| UCHIJA  | enderioconduitsrefinedstorage     | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                     | None                                     |
> 	| UCHIJA  | enderiointegrationforestry        | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                     | None                                     |
> 	| UCHIJA  | enderiointegrationticlate         | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                     | None                                     |
> 	| UCHIJA  | ftblib                            | 5.1.0.22                 | FTBLib-5.1.0.22.jar                           | None                                     |
> 	| UCHIJA  | enderiomachines                   | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                     | None                                     |
> 	| UCHIJA  | enderiopowertools                 | 5.0.26                   | EnderIO-1.12.2-5.0.26.jar                     | None                                     |
> 	| UCHIJA  | foamfix                           | 0.9.9.1-1.12.2           | foamfix-0.9.9.1-1.12.2-anarchy.jar            | None                                     |
> 	| UCHIJA  | ftbutilities                      | 5.1.0.27                 | FTBUtilities-5.1.0.27.jar                     | None                                     |
> 	| UCHIJA  | gamestages                        | 2.0.91                   | GameStages-1.12.2-2.0.91.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
> 	| UCHIJA  | guideapi                          | 1.12-2.1.5-60            | Guide-API-1.12-2.1.5-60.jar                   | None                                     |
> 	| UCHIJA  | initialinventory                  | 2.0.2                    | InitialInventory-3.0.0.jar                    | None                                     |
> 	| UCHIJA  | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
> 	| UCHIJA  | itemstages                        | 2.0.35                   | ItemStages-1.12.2-2.0.35.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
> 	| UCHIJA  | jaopcaagriculture                 | 1.12.2-1.2.1.13          | JAOPCAAgriculture-1.12.2-1.2.1.13.jar         | None                                     |
> 	| UCHIJA  | jaopca                            | 1.12.2-2.2.8.89          | JAOPCA-1.12.2-2.2.8.89.jar                    | None                                     |
> 	| UCHIJA  | oredictinit                       | 1.12.2-2.2.1.68          | JAOPCA-1.12.2-2.2.8.89.jar                    | None                                     |
> 	| UCHIJA  | journeymap                        | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                   | None                                     |
> 	| UCHIJA  | minetogether                      | unspecified              | minetogether-1.10.2-1.8.7.jar                 | None                                     |
> 	| UCHIJA  | minetogetherserver                | unspecified              | minetogether-1.10.2-1.8.7.jar                 | None                                     |
> 	| UCHIJA  | modnametooltip                    | 1.10.0                   | modnametooltip_1.12.2-1.10.0.jar              | None                                     |
> 	| UCHIJA  | mousetweaks                       | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                  | None                                     |
> 	| UCHIJA  | netherportalfix                   | 5.3.13                   | NetherPortalFix_1.12.1-5.3.13.jar             | None                                     |
> 	| UCHIJA  | notreepunching                    | 1.4.5                    | notreepunching-1.4.5.jar                      | None                                     |
> 	| UCHIJA  | orestages                         | 2.0.30                   | OreStages-1.12.2-2.0.30.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
> 	| UCHIJA  | harvestcraft                      | 1.12.2u                  | Pam's HarvestCraft 1.12.2u.jar                | None                                     |
> 	| UCHIJA  | planarartifice                    | 0.10                     | planarartifice-0.10.jar                       | None                                     |
> 	| UCHIJA  | tiffitlib                         | 1.0.0                    | tiffitlib-1.0.0.jar                           | None                                     |
> 	| UCHIJA  | progressiveboxes                  | 1.0.1                    | progressiveboxes-1.0.1.jar                    | None                                     |
> 	| UCHIJA  | questbook                         | 3.1.1-1.12               | questbook-3.1.1-1.12.jar                      | None                                     |
> 	| UCHIJA  | quickleafdecay                    | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar             | None                                     |
> 	| UCHIJA  | recipestages                      | 1.1.1                    | RecipeStages-1.1.1.jar                        | None                                     |
> 	| UCHIJA  | resourceloader                    | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar             | d72e0dd57935b3e9476212aea0c0df352dd76291 |
> 	| UCHIJA  | rftools                           | 7.53                     | rftools-1.12-7.53.jar                         | None                                     |
> 	| UCHIJA  | roguelike                         | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
> 	| UCHIJA  | sereneseasons                     | 1.2.3                    | SereneSeasons-1.12.2-1.2.3-universal.jar      | None                                     |
> 	| UCHIJA  | solcarrot                         | 1.3.1                    | solcarrot-1.12.2-1.3.3.jar                    | None                                     |
> 	| UCHIJA  | bq_standard                       | 3.4.143                  | StandardExpansion-3.4.143.jar                 | None                                     |
> 	| UCHIJA  | theoneprobe                       | 1.4.23                   | theoneprobe-1.12-1.4.23.jar                   | None                                     |
> 	| UCHIJA  | tinkersjei                        | 1.0                      | tinkersjei-1.0.jar                            | None                                     |
> 	| UCHIJA  | tinkerstages                      | 2.0.15                   | TinkerStages-1.12.2-2.0.15.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
> 	| UCHIJA  | tinkertoolleveling                | 1.12.2-1.0.5.DEV.30c7957 | TinkerToolLeveling-1.12.2-1.0.5.jar           | None                                     |
> 	| UCHIJA  | togetherforever                   | 1.0.2                    | togetherforever-1.12.2-1.0.10-17.jar          | None                                     |
> 	| UCHIJA  | topaddons                         | 1.12.2-1.7.0             | topaddons-1.12.2-1.7.0.jar                    | None                                     |
> 	| UCHIJA  | reauth                            | 3.6.0                    | reauth-3.6.0.jar                              | daba0ec4df71b6da841768c49fb873def208a1e3 |
> 	| UCHIJA  | tinkersurvival                    | 1.0.1.20                 | TinkerSurvival-1.12.2-1.0.1.20.jar            | 9cd6bcf5f667bff0b7825080f467db605192243c |
> 	| UCHIJA  | wrapup                            | 1.12-1.1.3               | WrapUp-1.12-1.1.3.jar                         | None                                     |
> 
> 	Loaded coremods (and transformers): 
> Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
>   invtweaks.forge.asm.ContainerTransformer
> AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
>   squeek.applecore.asm.TransformerModuleHandler
> EnderCorePlugin (EnderCore-1.12.2-0.5.31.jar)
>   com.enderio.core.common.transform.EnderCoreTransformer
>   com.enderio.core.common.transform.SimpleMixinPatcher
> LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
>   lumien.resourceloader.asm.ClassTransformer
> Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
>   pl.asie.foamfix.coremod.FoamFixTransformer
> SSLoadingPlugin (SereneSeasons-1.12.2-1.2.3-universal.jar)
>   sereneseasons.asm.transformer.EntityRendererTransformer
>   sereneseasons.asm.transformer.WorldTransformer
> 	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4459' Renderer: 'Intel(R) HD Graphics'
> 	Pulsar/tconstruct loaded Pulses: 
> 		- TinkerCommons (Enabled/Forced)
> 		- TinkerWorld (Enabled/Not Forced)
> 		- TinkerTools (Enabled/Not Forced)
> 		- TinkerHarvestTools (Enabled/Forced)
> 		- TinkerMeleeWeapons (Enabled/Forced)
> 		- TinkerRangedWeapons (Enabled/Forced)
> 		- TinkerModifiers (Enabled/Forced)
> 		- TinkerSmeltery (Enabled/Not Forced)
> 		- TinkerGadgets (Enabled/Not Forced)
> 		- TinkerOredict (Enabled/Forced)
> 		- TinkerIntegration (Enabled/Forced)
> 		- TinkerFluids (Enabled/Forced)
> 		- TinkerMaterials (Enabled/Forced)
> 		- TinkerModelRegister (Enabled/Forced)
> 		- theoneprobeIntegration (Enabled/Not Forced)
> 
> 	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
>                   * Optifine is installed. This is NOT supported.
>                  This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
> 
> 	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 	!!!You are looking at the diagnostics information, not at the crash.       !!!
> 	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
> 	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by forestbat** [comment]
You probably need to update your Java to 1.8_172.

**Comment by DaggerTM** [comment]
My java is fine... Minecraft uses 8.25 for some reason even though it's not installed.

But... I downgraded to forge 14.23.4.2704 and it didn't crash.... but the two mods, No Tree Punching, and Tinker Survival require forge beyond that so I can't use croparia...

**Comment by forestbat** [comment]
@DaggerTM Mojang is lazy to update Java because they don't know what will happen，so a old Java version will bring some trouble。

**Comment by DaggerTM** [comment]
I do plan on upgrading my Java today for now I’ll downgrade Tinker Survival and NTP to the versions that don’t need forge 2705+
